Repository kalviumcommunity/S82_Rahul_Capstone_ClickIn, pull requests merged in 2025-05, with the labels that each got.

#8 post api Initialized
  server/.gitignore
  server/config/db.js
  server/controllers/address.controller.js
  server/controllers/category.controller.js
  server/controllers/deliveryPartner.controller.js
  server/controllers/order.controller.js
  server/controllers/product.controller.js
  server/controllers/shopKeeper.controller.js
  server/controllers/user.controller.js
  server/routes/address.routes.js
  server/routes/category.routes.js
  server/routes/deliveryPartner.routes.js
  server/routes/order.routes.js
  server/routes/product.routes.js
  server/routes/shopKeeper.routes.js
  server/routes/user.routes.js
Labels: Review effort 2/5

#23 Backend deployed
  README.md
  server/controllers/user.controller.js
Labels: Review effort 1/5

#30 checked in bruno successfully
  server/controllers/user.controller.js
Labels: Review effort 2/5

#33 GraphQL: Fetching Data via Queries implemented
  ClickIn/clickin.bru
  client/.gitignore
  client/package-lock.json
  client/package.json
  client/src/App.jsx
  client/src/assets/fruits/1.png
  client/src/assets/fruits/2.png
  client/src/assets/fruits/3.png
  client/src/assets/fruits/4.png
  client/src/assets/fruits/5.png
  client/src/assets/fruits/6.png
  client/src/assets/fruits/7.png
  client/src/assets/fruits/8.png
  client/src/assets/fruits/logo.png
  client/src/assets/fruits/react.svg
  client/src/components/CategoryList.jsx
  client/src/components/Header.jsx
  client/src/components/Search/SearchBar.jsx
  client/src/components/Search/SuggestionList.jsx
  client/src/components/SearchBar.css
  client/src/hooks/useAutocomplete.js
  client/src/pages/Explore.css
  client/src/pages/Explore.jsx
  client/src/pages/GroceryToggle.css
  client/src/pages/GroceryToggle.jsx
  client/src/pages/Home.jsx
  client/src/pages/VendorToggle.css
  client/src/pages/VendorToggle.jsx
  client/src/pages/vendor/Settings.jsx
  server/app.js
  server/controllers/category.controller.js
  server/controllers/gemini.controller.js
  server/controllers/product.controller.js
  server/controllers/shopKeeper.controller.js
  server/controllers/user.controller.js
  server/gemini-autocomplete-backend/package-lock.json
  server/gemini-autocomplete-backend/package.json
  server/graphql/resolvers/category.resolvers.js
  server/graphql/resolvers/index.js
  server/graphql/resolvers/product.resolvers.js
  server/graphql/resolvers/shopkeeper.resolvers.js
  server/graphql/typeDefs/category.typeDefs.js
  server/graphql/typeDefs/index.js
  server/graphql/typeDefs/product.typeDefs.js
  server/graphql/typeDefs/shopkeeper.typeDefs.js
  server/middleware/multer.js
  server/package-lock.json
  server/package.json
  server/routes/category.routes.js
  server/routes/gemini.routes.js
  server/routes/product.routes.js
  server/routes/shopKeeper.routes.js
  server/routes/user.routes.js
  server/src/models/user.model.js
  server/src/services/geminiClient.js
  server/src/utils/authUtils.js
  server/src/utils/geminiAutocomplete.js
  server/src/utils/mail.js
Labels: Review effort 4/5

#34 GraphQL: Writing Data with Mutations
  server/graphql/resolvers/category.resolvers.js
  server/graphql/resolvers/index.js
  server/graphql/resolvers/product.resolvers.js
  server/graphql/resolvers/shopkeeper.resolvers.js
  server/graphql/typeDefs/category.typeDefs.js
  server/graphql/typeDefs/product.typeDefs.js
  server/graphql/typeDefs/shopkeeper.typeDefs.js
  server/src/utils/errorHandler.js
Labels: Review effort 2/5

#36 bug fixed
  server/app.js
  server/src/utils/authUtils.js
  server/src/utils/errorHandler.js
Labels: Review effort 2/5

#37 Frontend implemented
  ClickIn/clickin.bru
  client/src/App.jsx
  client/src/assets/image/background.jpg
  client/src/assets/image/bgimage.png
  client/src/assets/image/cloud.png
  client/src/assets/image/door.png
  client/src/assets/image/fifthImage.png
  client/src/assets/image/fourthImage.png
  client/src/assets/image/fruit.jpg
  client/src/assets/image/fruit1.png
  client/src/assets/image/generatedHeaderImage-1662578814159.jpg
  client/src/assets/image/homeImage.png
  client/src/assets/image/homefooter.png
  client/src/assets/image/index.jsx
  client/src/assets/image/leaf-1.png
  client/src/assets/image/leaf-6.png
  client/src/assets/image/leaf-8.png
  client/src/assets/image/line.png
  client/src/assets/image/logo-3.png
  client/src/assets/image/logo.png
  client/src/assets/image/newImage.png
  client/src/assets/image/page.jpg
  client/src/assets/image/thirdImage.png
  client/src/components/CategoryList.jsx
  client/src/components/Footer.jsx
  client/src/pages/Home1.jsx
  server/app.js
  server/controllers/address.controller.js
  server/src/utils/errorHandler.js
Labels: Review effort 3/5
